<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<PublishSingleFile>true</PublishSingleFile>
	<SelfContained>true</SelfContained>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="View\Images\Back.png" />
    <None Remove="View\Images\ClosingCross.png" />
    <None Remove="View\Images\CrossDark.png" />
    <None Remove="View\Images\CrossLight.png" />
    <None Remove="View\Images\Plus.png" />
    <None Remove="View\Images\SeparatorDark.png" />
    <None Remove="View\Images\SeparatorLight.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="View\Images\Back.png" />
    <Resource Include="View\Images\ClosingCross.png" />
    <Resource Include="View\Images\CrossDark.png" />
    <Resource Include="View\Images\CrossLight.png" />
    <Resource Include="View\Images\Plus.png" />
    <Resource Include="View\Images\SeparatorDark.png" />
    <Resource Include="View\Images\SeparatorLight.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Model\Data\DatabaseProvider\appsettings.json">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	</None>
    <None Update="Model\Data\DatabaseProvider\appsettings.example.json">
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
  </ItemGroup>

</Project>

